version: '3.6'

services: 
  wordpress:
    image: wordpress:5.5-php7.2-fpm
    build:
      context: .
      dockerfile: wordpress/Dockerfile
    container_name: ${APP_NAME}-wp
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${DB_TABLE_PREFIX}
    volumes:
      - ../.docker/wordpress/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ../web:/var/www/html
      - ../web/wp-config-sample.php:/var/www/html/wp-config-sample.php
      - ../web/wp-content/uploads:/var/www/html/wp-content/uploads:cached
      - ../web/wp-content/plugins:/var/www/html/wp-content/plugins:cached
      - ../web/wp-includes:/var/www/html/wp-includes:cached
      - ../web/wp-admin:/var/www/html/wp-admin:cached
    restart: unless-stopped
    command: > 
      bash -c '
        if [ ! -d "/var/www/html/wp-content/themes/${WP_THEME_NAME}" ]
        then
            echo "Directory /path/to/dir DOES NOT exists." 
            mv /var/www/html/wp-content/themes/default /var/www/html/wp-content/themes/${WP_THEME_NAME}
        fi
        php-fpm
      '

  nginx:
    image: nginx:latest
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: ${APP_NAME}-nginx
    ports:
      - 80:80
      - 443:443
    environment:
      MYSQL_HOST: ${DB_HOST}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ../.docker/nginx/default.conf:/tmp/default.template
      - ../.docker/certs:/etc/certs
      - ../web:/var/www/html
    depends_on:
      - wordpress
    restart: unless-stopped
    entrypoint: /bin/bash -c 'cat /tmp/default.template | sed "s/\\\$$domain/${DOMAIN}/g" > /etc/nginx/conf.d/default.conf && nginx -g "daemon off;"'
