version: '3.6'

services: 
  wordpress:
    image: wordpress:php8.0-fpm
    build:
      context: .
      dockerfile: wordpress/Dockerfile
    container_name: ${APP_NAME}-wp
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_TABLE_PREFIX: ${MYSQL_TABLE_PREFIX}
    volumes:
      - ../.docker/wordpress/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ../web:/var/www/html:rw,cached
      - ../web/wp-config-sample.php:/var/www/html/wp-config-sample.php
      - ../web/wp-content/uploads:/var/www/html/wp-content/uploads:cached
      - ../web/wp-content/plugins:/var/www/html/wp-content/plugins:cached
      - ../web/wp-includes:/var/www/html/wp-includes:cached
      - ../web/wp-admin:/var/www/html/wp-admin:cached
    restart: unless-stopped
    command: > 
      bash -c '
        if [ ! -d "/var/www/html/wp-content/themes/${THEME_NAME}" ]
        then
            echo "Directory /path/to/dir DOES NOT exists." 
            mv /var/www/html/wp-content/themes/default /var/www/html/wp-content/themes/${THEME_NAME}
        fi
        php-fpm
      '

  nginx:
    image: nginx:latest
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: ${APP_NAME}-nginx
    ports:
      - 80:80
      - 443:443
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_TABLE_PREFIX: ${MYSQL_TABLE_PREFIX}
    volumes:
      - ../.docker/nginx/default.conf:/tmp/default.template
      - ../.docker/certs:/etc/certs
      - ../web:/var/www/html:rw,cached
    depends_on:
      - wordpress
    restart: unless-stopped
    entrypoint: /bin/bash -c 'cat /tmp/default.template | sed "s/\\\$$domain/${DOMAIN}/g" > /etc/nginx/conf.d/default.conf && nginx -g "daemon off;"'
